// apps/reference-react/src/scenarios/AudioPlayerScenario.tsx
import React, { useEffect, useRef } from 'react';
import AudioPlayer from '@semi-v2.102.0/audio-player';
import ConfigProvider from '@semi-v2.102.0/config-provider';
import {
  AUDIO_PLAYER_COVER_DATA_URI,
  createSilentAudioDataUri,
  type ParityDirection,
  type ParityLocale,
  type ParityThemeMode,
} from '@workspace/test-infra';

const playlist = [
  {
    title: 'Parity track A',
    cover: AUDIO_PLAYER_COVER_DATA_URI,
    src: createSilentAudioDataUri(4),
  },
  {
    title: 'Parity track B',
    cover: AUDIO_PLAYER_COVER_DATA_URI,
    src: createSilentAudioDataUri(6),
  },
];

const localeMap = {
  'zh-CN': {
    code: 'zh-CN',
    AudioPlayer: {
      backward: '后退 ${skipDuration} 秒',
      forward: '前进 ${skipDuration} 秒',
      prev: '上一首',
      next: '下一首',
      loop: '循环播放',
      volume: '音量',
      mediaError: '音频加载失败',
    },
  },
  'en-US': {
    code: 'en-US',
    AudioPlayer: {
      backward: 'Backward ${skipDuration}s',
      forward: 'Forward ${skipDuration}s',
      prev: 'Previous',
      next: 'Next',
      loop: 'Loop',
      volume: 'Volume',
      mediaError: 'Audio load error',
    },
  },
};

export function AudioPlayerScenario({
  direction,
  locale,
  theme,
}: {
  direction: ParityDirection;
  locale: ParityLocale;
  theme: ParityThemeMode;
}): React.ReactElement {
  const popupContainerRef = useRef<HTMLDivElement | null>(null);

  if (typeof document !== 'undefined' && popupContainerRef.current === null) {
    popupContainerRef.current = document.createElement('div');
    popupContainerRef.current.dataset.testid = 'audio-player-popup-reference';
    document.body.appendChild(popupContainerRef.current);
  }

  useEffect(
    () => () => {
      popupContainerRef.current?.remove();
      popupContainerRef.current = null;
    },
    [],
  );

  return (
    <ConfigProvider
      direction={direction}
      locale={localeMap[locale]}
      getPopupContainer={() => popupContainerRef.current ?? document.body}
    >
      <div className="audio-player-scenario" data-testid="audio-player-reference">
        <section className="audio-player-scenario__card audio-player-scenario__main">
          <h3>Playlist / toolbar</h3>
          <AudioPlayer
            audioUrl={playlist}
            data-parity-target="audio-player-main"
            skipDuration={1}
            theme={theme}
          />
        </section>
        <section className="audio-player-scenario__card audio-player-scenario__compact">
          <h3>Compact / no toolbar</h3>
          <AudioPlayer
            audioUrl={{
              title: 'Compact track',
              cover: AUDIO_PLAYER_COVER_DATA_URI,
              src: createSilentAudioDataUri(4),
            }}
            data-parity-target="audio-player-compact"
            showToolbar={false}
            theme={theme}
          />
        </section>
      </div>
    </ConfigProvider>
  );
}

// apps/parity-vue/src/components/AudioPlayerScenario.vue
<script setup lang="ts">
import { onBeforeUnmount } from 'vue';
import { AudioPlayer } from '@aifuxi/semi-ui-vue/audio-player';
import { ConfigProvider, type SemiLocale } from '@aifuxi/semi-ui-vue/config-provider';
import {
  AUDIO_PLAYER_COVER_DATA_URI,
  createSilentAudioDataUri,
  type ParityDirection,
  type ParityLocale,
  type ParityThemeMode,
} from '@workspace/test-infra';

const props = defineProps<{
  direction: ParityDirection;
  locale: ParityLocale;
  theme: ParityThemeMode;
}>();
const playlist = [
  {
    title: 'Parity track A',
    cover: AUDIO_PLAYER_COVER_DATA_URI,
    src: createSilentAudioDataUri(4),
  },
  {
    title: 'Parity track B',
    cover: AUDIO_PLAYER_COVER_DATA_URI,
    src: createSilentAudioDataUri(6),
  },
];
const compactAudio = {
  title: 'Compact track',
  cover: AUDIO_PLAYER_COVER_DATA_URI,
  src: createSilentAudioDataUri(4),
};
const localeMap: Record<ParityLocale, SemiLocale> = {
  'zh-CN': {
    code: 'zh-CN',
    AudioPlayer: {
      backward: '后退 ${skipDuration} 秒',
      forward: '前进 ${skipDuration} 秒',
      prev: '上一首',
      next: '下一首',
      loop: '循环播放',
      volume: '音量',
      mediaError: '音频加载失败',
    },
  },
  'en-US': {
    code: 'en-US',
    AudioPlayer: {
      backward: 'Backward ${skipDuration}s',
      forward: 'Forward ${skipDuration}s',
      prev: 'Previous',
      next: 'Next',
      loop: 'Loop',
      volume: 'Volume',
      mediaError: 'Audio load error',
    },
  },
};

const popupContainer = typeof document === 'undefined' ? null : document.createElement('div');
if (popupContainer) {
  popupContainer.dataset.testid = 'audio-player-popup-vue';
  document.body.appendChild(popupContainer);
}
const getPopupContainer = () => popupContainer ?? document.body;

onBeforeUnmount(() => popupContainer?.remove());
</script>

<template>
  <ConfigProvider
    :direction="props.direction"
    :locale="localeMap[props.locale]"
    :get-popup-container="getPopupContainer"
  >
    <div class="audio-player-scenario" data-testid="audio-player-vue">
      <section class="audio-player-scenario__card audio-player-scenario__main">
        <h3>Playlist / toolbar</h3>
        <AudioPlayer
          :audio-url="playlist"
          data-parity-target="audio-player-main"
          :skip-duration="1"
          :theme="props.theme"
        />
      </section>
      <section class="audio-player-scenario__card audio-player-scenario__compact">
        <h3>Compact / no toolbar</h3>
        <AudioPlayer
          :audio-url="compactAudio"
          data-parity-target="audio-player-compact"
          :show-toolbar="false"
          :theme="props.theme"
        />
      </section>
    </div>
  </ConfigProvider>
</template>
