// apps/reference-react/src/scenarios/ToastScenario.tsx
import React, { useEffect } from 'react';
import Toast from '@semi-v2.102.0/toast';

export interface ToastScenarioProps {
  direction?: 'ltr' | 'rtl';
}

export function ToastScenario({ direction = 'ltr' }: ToastScenarioProps): React.ReactElement {
  useEffect(() => {
    Toast.destroyAll();
    Toast.info({
      className: 'toast-scenario__info',
      content: '同步已完成',
      direction,
      duration: 0,
      motion: false,
    });
    const timer = window.setTimeout(() => {
      Toast.warning({
        className: 'toast-scenario__warning',
        content: '访问凭证即将过期',
        direction,
        duration: 0,
        motion: false,
        theme: 'light',
      });
    });
    return () => {
      window.clearTimeout(timer);
      Toast.destroyAll();
    };
  }, [direction]);

  return (
    <div className="toast-scenario" data-testid="toast-reference">
      <p>Toast 渲染在当前 viewport 顶部中央。</p>
    </div>
  );
}

// apps/parity-vue/src/components/ToastScenario.vue
<script setup lang="ts">
import { Toast, type ConfigDirection } from '@aifuxi/semi-ui-vue';
import { onBeforeUnmount, onMounted } from 'vue';

const props = withDefaults(defineProps<{ direction?: ConfigDirection }>(), {
  direction: 'ltr',
});
let timer: number | undefined;

onMounted(() => {
  Toast.destroyAll();
  Toast.info({
    className: 'toast-scenario__info',
    content: '同步已完成',
    direction: props.direction,
    duration: 0,
    motion: false,
  });
  timer = window.setTimeout(() => {
    Toast.warning({
      className: 'toast-scenario__warning',
      content: '访问凭证即将过期',
      direction: props.direction,
      duration: 0,
      motion: false,
      theme: 'light',
    });
  });
});
onBeforeUnmount(() => {
  if (timer !== undefined) window.clearTimeout(timer);
  Toast.destroyAll();
});
</script>

<template>
  <div class="toast-scenario" data-testid="toast-vue">
    <p>Toast 渲染在当前 viewport 顶部中央。</p>
  </div>
</template>
