// apps/docs-vue/src/components/BreadcrumbScenario.vue
<script setup lang="ts">
import { shallowRef } from 'vue';
import { IconChevronRight, IconHome } from '@workspace/icons';
import { Breadcrumb, BreadcrumbItem, ConfigProvider } from '@workspace/ui';
import type { BreadcrumbItemInfo } from '@workspace/ui';
import type { ParityDirection } from '@workspace/test-infra';

const props = defineProps<{ direction: ParityDirection }>();
const status = shallowRef('等待操作');

function itemName(item: BreadcrumbItemInfo): string {
  return typeof item.name === 'string' ? item.name : String(item.path ?? '自定义项');
}
</script>

<template>
  <ConfigProvider :direction="props.direction">
    <div class="breadcrumb-scenario" data-testid="breadcrumb-vue">
      <div class="breadcrumb-scenario__canvas">
        <div class="breadcrumb-scenario__section">
          <span class="breadcrumb-scenario__label">基础与图标</span>
          <Breadcrumb
            aria-label="文档路径"
            data-parity-target="breadcrumb-basic"
            @click="(item) => (status = `父级：${itemName(item)}`)"
          >
            <BreadcrumbItem @click="(item) => (status = `子项：${itemName(item)}`)">
              <template #icon><IconHome /></template>
              首页
            </BreadcrumbItem>
            <BreadcrumbItem href="#components">组件</BreadcrumbItem>
            <BreadcrumbItem>面包屑</BreadcrumbItem>
          </Breadcrumb>
        </div>

        <div class="breadcrumb-scenario__section">
          <span class="breadcrumb-scenario__label">折叠与 Popover</span>
          <Breadcrumb
            data-parity-target="breadcrumb-collapsed"
            more-type="popover"
            @click="(item) => (status = `折叠项：${itemName(item)}`)"
          >
            <BreadcrumbItem>首页</BreadcrumbItem>
            <BreadcrumbItem>设计系统</BreadcrumbItem>
            <BreadcrumbItem>导航组件</BreadcrumbItem>
            <BreadcrumbItem>层级结构</BreadcrumbItem>
            <BreadcrumbItem>面包屑</BreadcrumbItem>
            <BreadcrumbItem>详情</BreadcrumbItem>
          </Breadcrumb>
        </div>

        <div class="breadcrumb-scenario__section">
          <span class="breadcrumb-scenario__label">宽松尺寸与受控激活</span>
          <Breadcrumb :active-index="1" :compact="false" data-parity-target="breadcrumb-loose">
            <template #separator><IconChevronRight size="small" /></template>
            <BreadcrumbItem>工作台</BreadcrumbItem>
            <BreadcrumbItem href="#current">当前页面</BreadcrumbItem>
            <BreadcrumbItem no-link>详情</BreadcrumbItem>
          </Breadcrumb>
        </div>
      </div>
      <output class="breadcrumb-scenario__status" aria-live="polite">{{ status }}</output>
    </div>
  </ConfigProvider>
</template>

// apps/reference-react/src/scenarios/BreadcrumbScenario.tsx
import React, { useState } from 'react';
import Breadcrumb, { type BreadcrumbItemInfo, type RouteProps } from '@semi-v2.102.0/breadcrumb';
import ConfigProvider from '@semi-v2.102.0/config-provider';
import { IconChevronRight, IconHome } from '@semi-v2.102.0/icons';
import type { ParityDirection } from '@workspace/test-infra';

function itemName(item: BreadcrumbItemInfo | RouteProps): string {
  return typeof item.name === 'string' ? item.name : String(item.path ?? '自定义项');
}

export function BreadcrumbScenario({
  direction,
}: {
  direction: ParityDirection;
}): React.ReactElement {
  const [status, setStatus] = useState('等待操作');
  return (
    <ConfigProvider direction={direction}>
      <div className="breadcrumb-scenario" data-testid="breadcrumb-reference">
        <div className="breadcrumb-scenario__canvas">
          <div className="breadcrumb-scenario__section">
            <span className="breadcrumb-scenario__label">基础与图标</span>
            <Breadcrumb
              aria-label="文档路径"
              data-parity-target="breadcrumb-basic"
              onClick={(item) => setStatus(`父级：${itemName(item)}`)}
            >
              <Breadcrumb.Item
                icon={<IconHome />}
                onClick={(item) => setStatus(`子项：${itemName(item)}`)}
              >
                首页
              </Breadcrumb.Item>
              <Breadcrumb.Item href="#components">组件</Breadcrumb.Item>
              <Breadcrumb.Item>面包屑</Breadcrumb.Item>
            </Breadcrumb>
          </div>

          <div className="breadcrumb-scenario__section">
            <span className="breadcrumb-scenario__label">折叠与 Popover</span>
            <Breadcrumb
              data-parity-target="breadcrumb-collapsed"
              moreType="popover"
              onClick={(item) => setStatus(`折叠项：${itemName(item)}`)}
            >
              <Breadcrumb.Item>首页</Breadcrumb.Item>
              <Breadcrumb.Item>设计系统</Breadcrumb.Item>
              <Breadcrumb.Item>导航组件</Breadcrumb.Item>
              <Breadcrumb.Item>层级结构</Breadcrumb.Item>
              <Breadcrumb.Item>面包屑</Breadcrumb.Item>
              <Breadcrumb.Item>详情</Breadcrumb.Item>
            </Breadcrumb>
          </div>

          <div className="breadcrumb-scenario__section">
            <span className="breadcrumb-scenario__label">宽松尺寸与受控激活</span>
            <Breadcrumb
              activeIndex={1}
              compact={false}
              data-parity-target="breadcrumb-loose"
              separator={<IconChevronRight size="small" />}
            >
              <Breadcrumb.Item>工作台</Breadcrumb.Item>
              <Breadcrumb.Item href="#current">当前页面</Breadcrumb.Item>
              <Breadcrumb.Item noLink>详情</Breadcrumb.Item>
            </Breadcrumb>
          </div>
        </div>
        <output className="breadcrumb-scenario__status" aria-live="polite">
          {status}
        </output>
      </div>
    </ConfigProvider>
  );
}
