// apps/docs-vue/src/components/NavigationScenario.vue
<script setup lang="ts">
import { Nav, type NavigationItems } from '@workspace/ui';

const items: NavigationItems = [
  { itemKey: 'home', text: '首页' },
  {
    itemKey: 'workspace',
    text: '工作台',
    items: [
      { itemKey: 'projects', text: '项目' },
      { itemKey: 'members', text: '成员' },
    ],
  },
  { itemKey: 'settings', text: '设置', disabled: true },
];
</script>

<template>
  <div class="navigation-scenario" data-testid="navigation-vue">
    <Nav
      :body-style="{ height: '224px' }"
      data-parity-target="navigation-root"
      :default-open-keys="['workspace']"
      :default-selected-keys="['projects']"
      :footer="{ collapseButton: true }"
      :header="{ text: 'Semi Console' }"
      :items="items"
    />
  </div>
</template>

// apps/reference-react/src/scenarios/NavigationScenario.tsx
import React from 'react';
import Navigation from '@semi-v2.102.0/navigation';

const items = [
  { itemKey: 'home', text: '首页' },
  {
    itemKey: 'workspace',
    text: '工作台',
    items: [
      { itemKey: 'projects', text: '项目' },
      { itemKey: 'members', text: '成员' },
    ],
  },
  { itemKey: 'settings', text: '设置', disabled: true },
];

export function NavigationScenario(): React.ReactElement {
  return (
    <div className="navigation-scenario" data-testid="navigation-reference">
      <Navigation
        bodyStyle={{ height: 224 }}
        data-parity-target="navigation-root"
        defaultOpenKeys={['workspace']}
        defaultSelectedKeys={['projects']}
        footer={{ collapseButton: true }}
        header={{ text: 'Semi Console' }}
        items={items}
      />
    </div>
  );
}
