// apps/docs-vue/src/components/TagScenario.vue
<script setup lang="ts">
import { SplitTagGroup, Tag, TagGroup, type TagData } from '@workspace/ui';

const tagList: TagData[] = [
  { tagKey: 'one', content: 'One', color: 'blue' },
  { tagKey: 'two', content: 'Two', color: 'cyan' },
  { tagKey: 'three', content: 'Three', color: 'teal' },
  { tagKey: 'four', content: 'Four', color: 'green' },
];
</script>

<template>
  <div class="tag-scenario" data-testid="tag-vue">
    <div class="tag-scenario__row" data-parity-target="tag-basic">
      <Tag color="blue" type="solid" size="large">Primary</Tag>
      <Tag color="amber" closable>Closable</Tag>
      <Tag color="violet" shape="circle">Rounded</Tag>
    </div>
    <div data-parity-target="tag-group">
      <TagGroup :max-tag-count="2" :tag-list="tagList" />
    </div>
    <div data-parity-target="tag-split">
      <SplitTagGroup aria-label="connected tags">
        <Tag color="blue" type="solid">One</Tag>
        <Tag color="cyan" type="solid">Two</Tag>
        <Tag color="teal" type="solid">Three</Tag>
      </SplitTagGroup>
    </div>
  </div>
</template>

// apps/reference-react/src/scenarios/TagScenario.tsx
import React from 'react';
import Tag from '@semi-v2.102.0/tag';
import TagGroup from '@semi-v2.102.0/tag-group';
import SplitTagGroup from '@semi-v2.102.0/split-tag-group';

const tagList = [
  { tagKey: 'one', children: 'One', color: 'blue' as const },
  { tagKey: 'two', children: 'Two', color: 'cyan' as const },
  { tagKey: 'three', children: 'Three', color: 'teal' as const },
  { tagKey: 'four', children: 'Four', color: 'green' as const },
];

export function TagScenario(): React.ReactElement {
  return (
    <div className="tag-scenario" data-testid="tag-reference">
      <div className="tag-scenario__row" data-parity-target="tag-basic">
        <Tag color="blue" type="solid" size="large">
          Primary
        </Tag>
        <Tag color="amber" closable>
          Closable
        </Tag>
        <Tag color="violet" shape="circle">
          Rounded
        </Tag>
      </div>
      <div data-parity-target="tag-group">
        <TagGroup maxTagCount={2} tagList={tagList} />
      </div>
      <div data-parity-target="tag-split">
        <SplitTagGroup aria-label="connected tags">
          <Tag color="blue" type="solid">
            One
          </Tag>
          <Tag color="cyan" type="solid">
            Two
          </Tag>
          <Tag color="teal" type="solid">
            Three
          </Tag>
        </SplitTagGroup>
      </div>
    </div>
  );
}
