// apps/reference-react/src/App.tsx
import React, { Suspense, type ComponentType } from 'react';
import {
  getParityScenario,
  getParityScenarioRuntimeProps,
  REFERENCE_BASELINE,
  type ParityScenarioOptions,
  type ParityScenarioRuntimeProps,
} from '@workspace/test-infra';
import { getLazyReactScenarioComponent } from './scenario-registry';

const DEFAULT_OPTIONS: ParityScenarioOptions = {
  scenarioId: 'harness-calibration',
  theme: 'light',
  direction: 'ltr',
  locale: 'zh-CN',
};

export type AppProps = Partial<ParityScenarioOptions> & {
  readonly scenarioComponent?: ComponentType<ParityScenarioRuntimeProps>;
};

function HarnessCalibration(): React.ReactElement {
  return (
    <div className="visual-calibration" data-testid="visual-calibration" aria-hidden="true">
      <span className="visual-calibration__primary" />
      <span className="visual-calibration__success" />
      <span className="visual-calibration__warning" />
    </div>
  );
}

export function App(props: AppProps): React.ReactElement {
  const { scenarioComponent, ...scenarioOptions } = props;
  const options = { ...DEFAULT_OPTIONS, ...scenarioOptions };
  const scenario = getParityScenario(options.scenarioId);
  const ScenarioComponent =
    scenarioComponent ??
    (scenario.id === 'harness-calibration'
      ? HarnessCalibration
      : getLazyReactScenarioComponent(options.scenarioId));
  const runtimeProps = getParityScenarioRuntimeProps(options);

  return (
    <main
      className={`workspace-shell${options.direction === 'rtl' ? ' semi-rtl' : ''}`}
      data-parity-framework="react"
      data-parity-scenario={scenario.id}
      data-reference-status={scenario.referenceStatus}
      data-vue-status={scenario.vueStatus}
      dir={options.direction}
    >
      <header className="workspace-header">
        <p className="workspace-shell__eyebrow">React reference target</p>
        <h1>Semi Design React 参考工作台</h1>
        <p>
          当前固定参考版本为 <code>{REFERENCE_BASELINE.tag}</code>，场景直接编译本地只读源码。
        </p>
      </header>

      <section className="scenario-panel" aria-labelledby="scenario-title">
        <div className="scenario-panel__heading">
          <div>
            <p className="scenario-panel__id">{scenario.id}</p>
            <h2 id="scenario-title">{scenario.title}</h2>
          </div>
          <span className="scenario-status" data-status={scenario.referenceStatus}>
            React {scenario.referenceStatus}
          </span>
        </div>
        <p className="scenario-panel__description">{scenario.description}</p>

        {ScenarioComponent && (scenarioComponent || scenario.id === 'harness-calibration') ? (
          <ScenarioComponent {...runtimeProps} />
        ) : ScenarioComponent ? (
          <Suspense fallback={<span data-parity-scenario-loading>场景加载中</span>}>
            <ScenarioComponent {...runtimeProps} />
          </Suspense>
        ) : null}
      </section>

      <dl className="runtime-evidence" aria-label="参考运行时证据">
        <div>
          <dt>commit</dt>
          <dd>{REFERENCE_BASELINE.commit}</dd>
        </div>
        <div>
          <dt>source</dt>
          <dd data-testid="reference-source">{scenario.referenceSource ?? 'shared harness'}</dd>
        </div>
      </dl>
    </main>
  );
}

// apps/parity-vue/src/App.vue
<script setup lang="ts">
import { computed, type Component } from 'vue';
import {
  getParityScenario,
  getParityScenarioRuntimeProps,
  REFERENCE_BASELINE,
  type ParityScenarioOptions,
} from '@workspace/test-infra';
import HarnessCalibration from './components/HarnessCalibration.vue';
import UnavailableScenario from './components/UnavailableScenario.vue';
import { getAsyncVueScenarioComponent } from './scenario-registry';

const props = withDefaults(
  defineProps<Partial<ParityScenarioOptions> & { scenarioComponent?: Component | undefined }>(),
  {
    scenarioId: 'harness-calibration',
    theme: 'light',
    direction: 'ltr',
    locale: 'zh-CN',
    scenarioComponent: undefined,
  },
);

const scenario = computed(() => getParityScenario(props.scenarioId));
const scenarioComponent = computed(
  () =>
    props.scenarioComponent ??
    (scenario.value.id === 'harness-calibration'
      ? HarnessCalibration
      : getAsyncVueScenarioComponent(props.scenarioId)),
);
const scenarioComponentProps = computed(() =>
  getParityScenarioRuntimeProps({
    scenarioId: props.scenarioId,
    theme: props.theme,
    direction: props.direction,
    locale: props.locale,
  }),
);
</script>

<template>
  <main
    :class="['workspace-shell', { 'semi-rtl': props.direction === 'rtl' }]"
    data-parity-framework="vue"
    :data-parity-scenario="scenario.id"
    :data-reference-status="scenario.referenceStatus"
    :data-vue-status="scenario.vueStatus"
    :dir="props.direction"
  >
    <header class="workspace-header">
      <p class="workspace-shell__eyebrow">Vue parity target</p>
      <h1>Semi UI Vue 对照工作台</h1>
      <p>
        当前固定参考版本为
        <code>{{ REFERENCE_BASELINE.tag }}</code>
        ，Vue 场景只在实现和证据齐全后进入可比较状态。
      </p>
    </header>

    <section class="scenario-panel" aria-labelledby="scenario-title">
      <div class="scenario-panel__heading">
        <div>
          <p class="scenario-panel__id">{{ scenario.id }}</p>
          <h2 id="scenario-title">{{ scenario.title }}</h2>
        </div>
        <span class="scenario-status" :data-status="scenario.vueStatus">
          Vue {{ scenario.vueStatus }}
        </span>
      </div>
      <p class="scenario-panel__description">{{ scenario.description }}</p>

      <Suspense v-if="scenarioComponent">
        <component :is="scenarioComponent" v-bind="scenarioComponentProps" />
        <template #fallback>
          <span data-parity-scenario-loading>场景加载中</span>
        </template>
      </Suspense>
      <UnavailableScenario
        v-else
        :scenario-id="scenario.id"
        :reference-source="scenario.referenceSource"
      />
    </section>

    <dl class="runtime-evidence" aria-label="Vue 对照状态">
      <div>
        <dt>commit</dt>
        <dd>{{ REFERENCE_BASELINE.commit }}</dd>
      </div>
      <div>
        <dt>source</dt>
        <dd data-testid="reference-source">{{ scenario.referenceSource ?? 'shared harness' }}</dd>
      </div>
    </dl>
  </main>
</template>
