// apps/reference-react/src/scenarios/FloatButtonScenario.tsx
import React, { useState } from 'react';
import FloatButton from '@semi-v2.102.0/float-button';
import FloatButtonGroup from '@semi-v2.102.0/float-button-group';
import { IconBell, IconCustomerSupport, IconHelpCircle, IconPlus } from '@semi-v2.102.0/icons';

const inlineStyle: React.CSSProperties = {
  position: 'relative',
  right: 'auto',
  bottom: 'auto',
};

export function FloatButtonScenario(): React.ReactElement {
  const [lastAction, setLastAction] = useState('暂无');
  const groupItems = [
    { content: '客服', icon: <IconCustomerSupport />, value: 'support' },
    { badge: { count: 6 }, content: '消息', icon: <IconBell />, value: 'message' },
    { content: '帮助', icon: <IconHelpCircle />, value: 'help' },
  ];

  return (
    <div className="float-button-scenario" data-testid="float-button-reference">
      <section className="float-button-scenario__section" aria-label="尺寸、形状与状态">
        <h3>尺寸、形状与状态</h3>
        <div className="float-button-scenario__row">
          {(['small', 'default', 'large'] as const).map((size) => (
            <FloatButton
              className={`float-button-target-${size}`}
              icon={<IconPlus />}
              key={size}
              size={size}
              style={inlineStyle}
              onClick={() => setLastAction(size)}
            />
          ))}
          <FloatButton
            className="float-button-target-square"
            icon={<IconPlus />}
            shape="square"
            style={inlineStyle}
          />
          <FloatButton
            colorful
            className="float-button-target-colorful"
            icon={<IconPlus />}
            style={inlineStyle}
          />
          <FloatButton
            className="float-button-target-disabled"
            disabled
            icon={<IconPlus />}
            style={inlineStyle}
            onClick={() => setLastAction('disabled')}
          />
          <FloatButton
            badge={{ count: 120, overflowCount: 99 }}
            className="float-button-target-badge"
            icon={<IconBell />}
            style={inlineStyle}
          />
        </div>
      </section>

      <section className="float-button-scenario__section" aria-label="悬浮按钮组">
        <h3>悬浮按钮组</h3>
        <FloatButtonGroup
          className="float-button-target-group"
          items={groupItems}
          style={inlineStyle}
          onClick={(value) => setLastAction(value)}
        />
      </section>

      <output className="scenario-action-output" aria-live="polite">
        最近操作：{lastAction}
      </output>
    </div>
  );
}

// apps/docs-vue/src/components/FloatButtonScenario.vue
<script setup lang="ts">
import { h, shallowRef, type CSSProperties } from 'vue';
import { IconBell, IconCustomerSupport, IconHelpCircle, IconPlus } from '@aifuxi/semi-icons-vue';
import {
  FloatButton,
  FloatButtonGroup,
  type FloatButtonGroupItem,
  type FloatButtonSize,
} from '@aifuxi/semi-ui-vue';

const sizes: readonly FloatButtonSize[] = ['small', 'default', 'large'];
const inlineStyle: CSSProperties = {
  position: 'relative',
  right: 'auto',
  bottom: 'auto',
};
const groupItems: readonly FloatButtonGroupItem[] = [
  { content: '客服', icon: h(IconCustomerSupport), value: 'support' },
  { badge: { count: 6 }, content: '消息', icon: h(IconBell), value: 'message' },
  { content: '帮助', icon: h(IconHelpCircle), value: 'help' },
];
const lastAction = shallowRef('暂无');
</script>

<template>
  <div class="float-button-scenario" data-testid="float-button-vue">
    <section class="float-button-scenario__section" aria-label="尺寸、形状与状态">
      <h3>尺寸、形状与状态</h3>
      <div class="float-button-scenario__row">
        <FloatButton
          v-for="size in sizes"
          :key="size"
          :class="`float-button-target-${size}`"
          :size="size"
          :style="inlineStyle"
          @click="lastAction = size"
        >
          <template #icon><IconPlus /></template>
        </FloatButton>
        <FloatButton class="float-button-target-square" shape="square" :style="inlineStyle">
          <template #icon><IconPlus /></template>
        </FloatButton>
        <FloatButton colorful class="float-button-target-colorful" :style="inlineStyle">
          <template #icon><IconPlus /></template>
        </FloatButton>
        <FloatButton
          disabled
          class="float-button-target-disabled"
          :style="inlineStyle"
          @click="lastAction = 'disabled'"
        >
          <template #icon><IconPlus /></template>
        </FloatButton>
        <FloatButton
          :badge="{ count: 120, overflowCount: 99 }"
          class="float-button-target-badge"
          :style="inlineStyle"
        >
          <template #icon><IconBell /></template>
        </FloatButton>
      </div>
    </section>

    <section class="float-button-scenario__section" aria-label="悬浮按钮组">
      <h3>悬浮按钮组</h3>
      <FloatButtonGroup
        class="float-button-target-group"
        :items="groupItems"
        :style="inlineStyle"
        @click="lastAction = $event"
      />
    </section>

    <output class="scenario-action-output" aria-live="polite"> 最近操作：{{ lastAction }} </output>
  </div>
</template>
