// apps/reference-react/src/scenarios/ScrollListScenario.tsx
import React, { useState } from 'react';
import ScrollList from '@semi-v2.102.0/scroll-list';
import ScrollItem from '@semi-v2.102.0/scroll-item';
import type { ScrollItemData, ScrollItemSelectData } from '@semi-v2.102.0/scroll-list';

const periods: ScrollItemData[] = [
  { value: 'AM', transform: () => 'Morning' },
  { value: 'PM' },
  { value: 'Night', disabled: true },
];
const hours: ScrollItemData[] = Array.from({ length: 8 }, (_, index) => ({
  value: index + 1,
  disabled: index === 5,
}));
const minutes: ScrollItemData[] = Array.from({ length: 8 }, (_, index) => ({
  value: index * 5,
  disabled: index === 3,
}));

export function ScrollListScenario(): React.ReactElement {
  const [normalPeriod, setNormalPeriod] = useState(0);
  const [normalHour, setNormalHour] = useState(2);
  const [wheelPeriod, setWheelPeriod] = useState(1);
  const [wheelHour, setWheelHour] = useState(3);
  const [wheelMinute, setWheelMinute] = useState(4);

  const selectNormal = (data: ScrollItemSelectData) => {
    if (data.type === 'normal-period') setNormalPeriod(data.index);
    if (data.type === 'normal-hour') setNormalHour(data.index);
  };
  const selectWheel = (data: ScrollItemSelectData) => {
    if (data.type === 'wheel-period') setWheelPeriod(data.index);
    if (data.type === 'wheel-hour') setWheelHour(data.index);
    if (data.type === 'wheel-minute') setWheelMinute(data.index);
  };

  return (
    <div className="scroll-list-scenario" data-testid="scroll-list-reference">
      <section data-parity-target="scroll-list-normal">
        <ScrollList bodyHeight={180} header="Normal columns" footer={<span>Click to select</span>}>
          <ScrollItem
            aria-label="Normal period"
            list={periods}
            mode="normal"
            onSelect={selectNormal}
            selectedIndex={normalPeriod}
            type="normal-period"
          />
          <ScrollItem
            aria-label="Normal hour"
            list={hours}
            mode="normal"
            onSelect={selectNormal}
            selectedIndex={normalHour}
            transform={(value) => `${String(value)} h`}
            type="normal-hour"
          />
        </ScrollList>
      </section>
      <section data-parity-target="scroll-list-wheel">
        <ScrollList bodyHeight={180} header="Wheel columns" footer={<span>Scroll to select</span>}>
          <ScrollItem
            aria-label="Wheel period"
            list={periods}
            mode="wheel"
            motion={false}
            onSelect={selectWheel}
            selectedIndex={wheelPeriod}
            type="wheel-period"
          />
          <ScrollItem
            aria-label="Wheel hour"
            cycled
            list={hours}
            mode="wheel"
            motion={false}
            onSelect={selectWheel}
            selectedIndex={wheelHour}
            type="wheel-hour"
          />
          <ScrollItem
            aria-label="Wheel minute"
            list={minutes}
            mode="wheel"
            motion={false}
            onSelect={selectWheel}
            selectedIndex={wheelMinute}
            transform={(value) => `${String(value)} min`}
            type="wheel-minute"
          />
        </ScrollList>
      </section>
    </div>
  );
}

// apps/docs-vue/src/components/ScrollListScenario.vue
<script setup lang="ts">
import { shallowRef } from 'vue';

import {
  ScrollItem,
  ScrollList,
  type ScrollItemData,
  type ScrollItemSelectData,
} from '@aifuxi/semi-ui-vue';

const periods: ScrollItemData[] = [
  { value: 'AM', transform: () => 'Morning' },
  { value: 'PM' },
  { value: 'Night', disabled: true },
];
const hours: ScrollItemData[] = Array.from({ length: 8 }, (_, index) => ({
  value: index + 1,
  disabled: index === 5,
}));
const minutes: ScrollItemData[] = Array.from({ length: 8 }, (_, index) => ({
  value: index * 5,
  disabled: index === 3,
}));

const normalPeriod = shallowRef(0);
const normalHour = shallowRef(2);
const wheelPeriod = shallowRef(1);
const wheelHour = shallowRef(3);
const wheelMinute = shallowRef(4);

function selectNormal(data: ScrollItemSelectData): void {
  if (data.type === 'normal-period') normalPeriod.value = data.index;
  if (data.type === 'normal-hour') normalHour.value = data.index;
}

function selectWheel(data: ScrollItemSelectData): void {
  if (data.type === 'wheel-period') wheelPeriod.value = data.index;
  if (data.type === 'wheel-hour') wheelHour.value = data.index;
  if (data.type === 'wheel-minute') wheelMinute.value = data.index;
}
</script>

<template>
  <div class="scroll-list-scenario" data-testid="scroll-list-vue">
    <section data-parity-target="scroll-list-normal">
      <ScrollList :body-height="180">
        <template #header>Normal columns</template>
        <ScrollItem
          aria-label="Normal period"
          :list="periods"
          mode="normal"
          :selected-index="normalPeriod"
          type="normal-period"
          @select="selectNormal"
        />
        <ScrollItem
          aria-label="Normal hour"
          :list="hours"
          mode="normal"
          :selected-index="normalHour"
          :transform="(value) => `${String(value)} h`"
          type="normal-hour"
          @select="selectNormal"
        />
        <template #footer><span>Click to select</span></template>
      </ScrollList>
    </section>
    <section data-parity-target="scroll-list-wheel">
      <ScrollList :body-height="180">
        <template #header>Wheel columns</template>
        <ScrollItem
          aria-label="Wheel period"
          :list="periods"
          mode="wheel"
          :motion="false"
          :selected-index="wheelPeriod"
          type="wheel-period"
          @select="selectWheel"
        />
        <ScrollItem
          aria-label="Wheel hour"
          cycled
          :list="hours"
          mode="wheel"
          :motion="false"
          :selected-index="wheelHour"
          type="wheel-hour"
          @select="selectWheel"
        />
        <ScrollItem
          aria-label="Wheel minute"
          :list="minutes"
          mode="wheel"
          :motion="false"
          :selected-index="wheelMinute"
          :transform="(value) => `${String(value)} min`"
          type="wheel-minute"
          @select="selectWheel"
        />
        <template #footer><span>Scroll to select</span></template>
      </ScrollList>
    </section>
  </div>
</template>
