// apps/docs-vue/src/App.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  getParityScenario,
  REFERENCE_BASELINE,
  type ParityScenarioOptions,
} from '@workspace/test-infra';
import AnchorScenario from './components/AnchorScenario.vue';
import AvatarScenario from './components/AvatarScenario.vue';
import BadgeScenario from './components/BadgeScenario.vue';
import CalendarScenario from './components/CalendarScenario.vue';
import CardScenario from './components/CardScenario.vue';
import CarouselScenario from './components/CarouselScenario.vue';
import CollapsibleScenario from './components/CollapsibleScenario.vue';
import CropperScenario from './components/CropperScenario.vue';
import DescriptionsScenario from './components/DescriptionsScenario.vue';
import DropdownScenario from './components/DropdownScenario.vue';
import EmptyScenario from './components/EmptyScenario.vue';
import HighlightScenario from './components/HighlightScenario.vue';
import ImageScenario from './components/ImageScenario.vue';
import ListScenario from './components/ListScenario.vue';
import ModalScenario from './components/ModalScenario.vue';
import OverflowListScenario from './components/OverflowListScenario.vue';
import PopoverScenario from './components/PopoverScenario.vue';
import ScrollListScenario from './components/ScrollListScenario.vue';
import SideSheetScenario from './components/SideSheetScenario.vue';
import TableScenario from './components/TableScenario.vue';
import TagScenario from './components/TagScenario.vue';
import TimelineScenario from './components/TimelineScenario.vue';
import BannerScenario from './components/BannerScenario.vue';
import NotificationScenario from './components/NotificationScenario.vue';
import IllustrationsScenario from './components/IllustrationsScenario.vue';
import BackTopScenario from './components/BackTopScenario.vue';
import BreadcrumbScenario from './components/BreadcrumbScenario.vue';
import AutoCompleteScenario from './components/AutoCompleteScenario.vue';
import ButtonTypesScenario from './components/ButtonTypesScenario.vue';
import ButtonContractScenario from './components/ButtonContractScenario.vue';
import CheckboxScenario from './components/CheckboxScenario.vue';
import ConfigProviderScenario from './components/ConfigProviderScenario.vue';
import DividerScenario from './components/DividerScenario.vue';
import FloatButtonScenario from './components/FloatButtonScenario.vue';
import GridScenario from './components/GridScenario.vue';
import IconScenario from './components/IconScenario.vue';
import LayoutScenario from './components/LayoutScenario.vue';
import InputScenario from './components/InputScenario.vue';
import InputNumberScenario from './components/InputNumberScenario.vue';
import PinCodeScenario from './components/PinCodeScenario.vue';
import PaginationScenario from './components/PaginationScenario.vue';
import RadioScenario from './components/RadioScenario.vue';
import RatingScenario from './components/RatingScenario.vue';
import ResizableScenario from './components/ResizableScenario.vue';
import SelectScenario from './components/SelectScenario.vue';
import SliderScenario from './components/SliderScenario.vue';
import SpaceScenario from './components/SpaceScenario.vue';
import StepsScenario from './components/StepsScenario.vue';
import TabsScenario from './components/TabsScenario.vue';
import TreeScenario from './components/TreeScenario.vue';
import SwitchScenario from './components/SwitchScenario.vue';
import TagInputScenario from './components/TagInputScenario.vue';
import TimePickerScenario from './components/TimePickerScenario.vue';
import TooltipScenario from './components/TooltipScenario.vue';
import TypographyScenario from './components/TypographyScenario.vue';
import HarnessCalibration from './components/HarnessCalibration.vue';
import UnavailableScenario from './components/UnavailableScenario.vue';

const props = withDefaults(defineProps<Partial<ParityScenarioOptions>>(), {
  scenarioId: 'harness-calibration',
  theme: 'light',
  direction: 'ltr',
  locale: 'zh-CN',
});

const scenario = computed(() => getParityScenario(props.scenarioId));
</script>

<template>
  <main
    :class="['workspace-shell', { 'semi-rtl': props.direction === 'rtl' }]"
    data-parity-framework="vue"
    :data-parity-scenario="scenario.id"
    :data-reference-status="scenario.referenceStatus"
    :data-vue-status="scenario.vueStatus"
    :dir="props.direction"
  >
    <header class="workspace-header">
      <p class="workspace-shell__eyebrow">Vue parity target</p>
      <h1>Semi UI Vue 对照工作台</h1>
      <p>
        当前固定参考版本为
        <code>{{ REFERENCE_BASELINE.tag }}</code>
        ，Vue 场景只在实现和证据齐全后进入可比较状态。
      </p>
    </header>

    <section class="scenario-panel" aria-labelledby="scenario-title">
      <div class="scenario-panel__heading">
        <div>
          <p class="scenario-panel__id">{{ scenario.id }}</p>
          <h2 id="scenario-title">{{ scenario.title }}</h2>
        </div>
        <span class="scenario-status" :data-status="scenario.vueStatus">
          Vue {{ scenario.vueStatus }}
        </span>
      </div>
      <p class="scenario-panel__description">{{ scenario.description }}</p>

      <HarnessCalibration v-if="scenario.id === 'harness-calibration'" />
      <AnchorScenario v-else-if="scenario.id === 'anchor'" :direction="props.direction" />
      <AvatarScenario v-else-if="scenario.id === 'avatar'" />
      <BadgeScenario v-else-if="scenario.id === 'badge'" :direction="props.direction" />
      <CalendarScenario
        v-else-if="scenario.id === 'calendar'"
        :direction="props.direction"
        :locale="props.locale"
      />
      <CardScenario v-else-if="scenario.id === 'card'" />
      <CarouselScenario v-else-if="scenario.id === 'carousel'" />
      <CollapsibleScenario v-else-if="scenario.id === 'collapsible'" />
      <CropperScenario v-else-if="scenario.id === 'cropper'" />
      <DescriptionsScenario v-else-if="scenario.id === 'descriptions'" />
      <DropdownScenario v-else-if="scenario.id === 'dropdown'" />
      <EmptyScenario v-else-if="scenario.id === 'empty'" />
      <HighlightScenario v-else-if="scenario.id === 'highlight'" />
      <ImageScenario v-else-if="scenario.id === 'image'" />
      <ListScenario v-else-if="scenario.id === 'list'" />
      <ModalScenario v-else-if="scenario.id === 'modal'" :direction="props.direction" />
      <OverflowListScenario v-else-if="scenario.id === 'overflow-list'" />
      <PopoverScenario v-else-if="scenario.id === 'popover'" :direction="props.direction" />
      <ScrollListScenario v-else-if="scenario.id === 'scroll-list'" />
      <SideSheetScenario v-else-if="scenario.id === 'side-sheet'" :direction="props.direction" />
      <TableScenario v-else-if="scenario.id === 'table'" :direction="props.direction" />
      <TagScenario v-else-if="scenario.id === 'tag'" />
      <TimelineScenario v-else-if="scenario.id === 'timeline'" />
      <BannerScenario v-else-if="scenario.id === 'banner'" />
      <NotificationScenario
        v-else-if="scenario.id === 'notification'"
        :direction="props.direction"
      />
      <IllustrationsScenario v-else-if="scenario.id === 'illustrations'" />
      <BackTopScenario v-else-if="scenario.id === 'back-top'" :direction="props.direction" />
      <BreadcrumbScenario v-else-if="scenario.id === 'breadcrumb'" :direction="props.direction" />
      <AutoCompleteScenario v-else-if="scenario.id === 'auto-complete'" />
      <ButtonTypesScenario v-else-if="scenario.id === 'button-types'" />
      <ButtonContractScenario v-else-if="scenario.id === 'button-contract'" />
      <CheckboxScenario v-else-if="scenario.id === 'checkbox'" />
      <ConfigProviderScenario v-else-if="scenario.id === 'config-provider'" />
      <DividerScenario v-else-if="scenario.id === 'divider'" />
      <FloatButtonScenario v-else-if="scenario.id === 'float-button'" />
      <GridScenario v-else-if="scenario.id === 'grid'" />
      <IconScenario v-else-if="scenario.id === 'icon'" />
      <LayoutScenario v-else-if="scenario.id === 'layout'" />
      <InputScenario v-else-if="scenario.id === 'input'" />
      <InputNumberScenario v-else-if="scenario.id === 'input-number'" />
      <PinCodeScenario v-else-if="scenario.id === 'pin-code'" />
      <PaginationScenario
        v-else-if="scenario.id === 'pagination'"
        :direction="props.direction"
        :locale="props.locale"
      />
      <RadioScenario v-else-if="scenario.id === 'radio'" />
      <RatingScenario v-else-if="scenario.id === 'rating'" />
      <ResizableScenario v-else-if="scenario.id === 'resizable'" />
      <SelectScenario v-else-if="scenario.id === 'select'" />
      <SliderScenario v-else-if="scenario.id === 'slider'" :direction="props.direction" />
      <SpaceScenario v-else-if="scenario.id === 'space'" />
      <StepsScenario v-else-if="scenario.id === 'steps'" />
      <TabsScenario v-else-if="scenario.id === 'tabs'" />
      <TreeScenario
        v-else-if="scenario.id === 'tree'"
        :direction="props.direction"
        :locale="props.locale"
      />
      <SwitchScenario v-else-if="scenario.id === 'switch'" />
      <TagInputScenario v-else-if="scenario.id === 'tag-input'" />
      <TimePickerScenario v-else-if="scenario.id === 'time-picker'" />
      <TooltipScenario v-else-if="scenario.id === 'tooltip'" />
      <TypographyScenario v-else-if="scenario.id === 'typography'" />
      <UnavailableScenario
        v-else
        :scenario-id="scenario.id"
        :reference-source="scenario.referenceSource"
      />
    </section>

    <dl class="runtime-evidence" aria-label="Vue 对照状态">
      <div>
        <dt>commit</dt>
        <dd>{{ REFERENCE_BASELINE.commit }}</dd>
      </div>
      <div>
        <dt>source</dt>
        <dd data-testid="reference-source">{{ scenario.referenceSource ?? 'shared harness' }}</dd>
      </div>
    </dl>
  </main>
</template>

// apps/reference-react/src/App.tsx
import React from 'react';
import {
  getParityScenario,
  REFERENCE_BASELINE,
  type ParityScenarioOptions,
} from '@workspace/test-infra';
import { AnchorScenario } from './scenarios/AnchorScenario';
import { AvatarScenario } from './scenarios/AvatarScenario';
import { BadgeScenario } from './scenarios/BadgeScenario';
import { CalendarScenario } from './scenarios/CalendarScenario';
import { CardScenario } from './scenarios/CardScenario';
import { CarouselScenario } from './scenarios/CarouselScenario';
import { CollapsibleScenario } from './scenarios/CollapsibleScenario';
import { CropperScenario } from './scenarios/CropperScenario';
import { DescriptionsScenario } from './scenarios/DescriptionsScenario';
import { DropdownScenario } from './scenarios/DropdownScenario';
import { EmptyScenario } from './scenarios/EmptyScenario';
import { HighlightScenario } from './scenarios/HighlightScenario';
import { ImageScenario } from './scenarios/ImageScenario';
import { ListScenario } from './scenarios/ListScenario';
import { ModalScenario } from './scenarios/ModalScenario';
import { OverflowListScenario } from './scenarios/OverflowListScenario';
import { PopoverScenario } from './scenarios/PopoverScenario';
import { ScrollListScenario } from './scenarios/ScrollListScenario';
import { SideSheetScenario } from './scenarios/SideSheetScenario';
import { TableScenario } from './scenarios/TableScenario';
import { TagScenario } from './scenarios/TagScenario';
import { TimelineScenario } from './scenarios/TimelineScenario';
import { IllustrationsScenario } from './scenarios/IllustrationsScenario';
import { BackTopScenario } from './scenarios/BackTopScenario';
import { BreadcrumbScenario } from './scenarios/BreadcrumbScenario';
import { AutoCompleteScenario } from './scenarios/AutoCompleteScenario';
import { ButtonTypesScenario } from './scenarios/ButtonTypesScenario';
import { ButtonContractScenario } from './scenarios/ButtonContractScenario';
import { CheckboxScenario } from './scenarios/CheckboxScenario';
import { ConfigProviderScenario } from './scenarios/ConfigProviderScenario';
import { DividerScenario } from './scenarios/DividerScenario';
import { FloatButtonScenario } from './scenarios/FloatButtonScenario';
import { GridScenario } from './scenarios/GridScenario';
import { IconScenario } from './scenarios/IconScenario';
import { LayoutScenario } from './scenarios/LayoutScenario';
import { InputScenario } from './scenarios/InputScenario';
import { InputNumberScenario } from './scenarios/InputNumberScenario';
import { PinCodeScenario } from './scenarios/PinCodeScenario';
import { PaginationScenario } from './scenarios/PaginationScenario';
import { RadioScenario } from './scenarios/RadioScenario';
import { RatingScenario } from './scenarios/RatingScenario';
import { ResizableScenario } from './scenarios/ResizableScenario';
import { SelectScenario } from './scenarios/SelectScenario';
import { SliderScenario } from './scenarios/SliderScenario';
import { SpaceScenario } from './scenarios/SpaceScenario';
import { StepsScenario } from './scenarios/StepsScenario';
import { TabsScenario } from './scenarios/TabsScenario';
import { TreeScenario } from './scenarios/TreeScenario';
import { SwitchScenario } from './scenarios/SwitchScenario';
import { TagInputScenario } from './scenarios/TagInputScenario';
import { TimePickerScenario } from './scenarios/TimePickerScenario';
import { TooltipScenario } from './scenarios/TooltipScenario';
import { TypographyScenario } from './scenarios/TypographyScenario';

const DEFAULT_OPTIONS: ParityScenarioOptions = {
  scenarioId: 'harness-calibration',
  theme: 'light',
  direction: 'ltr',
  locale: 'zh-CN',
};

export type AppProps = Partial<ParityScenarioOptions>;

function HarnessCalibration(): React.ReactElement {
  return (
    <div className="visual-calibration" data-testid="visual-calibration" aria-hidden="true">
      <span className="visual-calibration__primary" />
      <span className="visual-calibration__success" />
      <span className="visual-calibration__warning" />
    </div>
  );
}

export function App(props: AppProps): React.ReactElement {
  const options = { ...DEFAULT_OPTIONS, ...props };
  const scenario = getParityScenario(options.scenarioId);

  return (
    <main
      className={`workspace-shell${options.direction === 'rtl' ? ' semi-rtl' : ''}`}
      data-parity-framework="react"
      data-parity-scenario={scenario.id}
      data-reference-status={scenario.referenceStatus}
      data-vue-status={scenario.vueStatus}
      dir={options.direction}
    >
      <header className="workspace-header">
        <p className="workspace-shell__eyebrow">React reference target</p>
        <h1>Semi Design React 参考工作台</h1>
        <p>
          当前固定参考版本为 <code>{REFERENCE_BASELINE.tag}</code>，场景直接编译本地只读源码。
        </p>
      </header>

      <section className="scenario-panel" aria-labelledby="scenario-title">
        <div className="scenario-panel__heading">
          <div>
            <p className="scenario-panel__id">{scenario.id}</p>
            <h2 id="scenario-title">{scenario.title}</h2>
          </div>
          <span className="scenario-status" data-status={scenario.referenceStatus}>
            React {scenario.referenceStatus}
          </span>
        </div>
        <p className="scenario-panel__description">{scenario.description}</p>

        {scenario.id === 'harness-calibration' ? <HarnessCalibration /> : null}
        {scenario.id === 'anchor' ? <AnchorScenario direction={options.direction} /> : null}
        {scenario.id === 'avatar' ? <AvatarScenario /> : null}
        {scenario.id === 'badge' ? <BadgeScenario direction={options.direction} /> : null}
        {scenario.id === 'calendar' ? (
          <CalendarScenario direction={options.direction} locale={options.locale} />
        ) : null}
        {scenario.id === 'card' ? <CardScenario /> : null}
        {scenario.id === 'carousel' ? <CarouselScenario /> : null}
        {scenario.id === 'collapsible' ? <CollapsibleScenario /> : null}
        {scenario.id === 'cropper' ? <CropperScenario /> : null}
        {scenario.id === 'descriptions' ? <DescriptionsScenario /> : null}
        {scenario.id === 'dropdown' ? <DropdownScenario /> : null}
        {scenario.id === 'empty' ? <EmptyScenario /> : null}
        {scenario.id === 'highlight' ? <HighlightScenario /> : null}
        {scenario.id === 'image' ? <ImageScenario /> : null}
        {scenario.id === 'list' ? <ListScenario /> : null}
        {scenario.id === 'modal' ? <ModalScenario direction={options.direction} /> : null}
        {scenario.id === 'overflow-list' ? <OverflowListScenario /> : null}
        {scenario.id === 'popover' ? <PopoverScenario direction={options.direction} /> : null}
        {scenario.id === 'scroll-list' ? <ScrollListScenario /> : null}
        {scenario.id === 'side-sheet' ? <SideSheetScenario direction={options.direction} /> : null}
        {scenario.id === 'table' ? <TableScenario direction={options.direction} /> : null}
        {scenario.id === 'tag' ? <TagScenario /> : null}
        {scenario.id === 'timeline' ? <TimelineScenario /> : null}
        {scenario.id === 'illustrations' ? <IllustrationsScenario /> : null}
        {scenario.id === 'back-top' ? <BackTopScenario direction={options.direction} /> : null}
        {scenario.id === 'breadcrumb' ? <BreadcrumbScenario direction={options.direction} /> : null}
        {scenario.id === 'auto-complete' ? <AutoCompleteScenario /> : null}
        {scenario.id === 'button-types' ? <ButtonTypesScenario /> : null}
        {scenario.id === 'button-contract' ? <ButtonContractScenario /> : null}
        {scenario.id === 'checkbox' ? <CheckboxScenario /> : null}
        {scenario.id === 'config-provider' ? <ConfigProviderScenario /> : null}
        {scenario.id === 'divider' ? <DividerScenario /> : null}
        {scenario.id === 'float-button' ? <FloatButtonScenario /> : null}
        {scenario.id === 'grid' ? <GridScenario /> : null}
        {scenario.id === 'icon' ? <IconScenario /> : null}
        {scenario.id === 'layout' ? <LayoutScenario /> : null}
        {scenario.id === 'input' ? <InputScenario /> : null}
        {scenario.id === 'input-number' ? <InputNumberScenario /> : null}
        {scenario.id === 'pin-code' ? <PinCodeScenario /> : null}
        {scenario.id === 'pagination' ? (
          <PaginationScenario direction={options.direction} locale={options.locale} />
        ) : null}
        {scenario.id === 'radio' ? <RadioScenario /> : null}
        {scenario.id === 'rating' ? <RatingScenario /> : null}
        {scenario.id === 'resizable' ? <ResizableScenario /> : null}
        {scenario.id === 'select' ? <SelectScenario /> : null}
        {scenario.id === 'slider' ? <SliderScenario direction={options.direction} /> : null}
        {scenario.id === 'space' ? <SpaceScenario /> : null}
        {scenario.id === 'steps' ? <StepsScenario /> : null}
        {scenario.id === 'tabs' ? <TabsScenario /> : null}
        {scenario.id === 'tree' ? (
          <TreeScenario direction={options.direction} locale={options.locale} />
        ) : null}
        {scenario.id === 'switch' ? <SwitchScenario /> : null}
        {scenario.id === 'tag-input' ? <TagInputScenario /> : null}
        {scenario.id === 'time-picker' ? <TimePickerScenario /> : null}
        {scenario.id === 'tooltip' ? <TooltipScenario /> : null}
        {scenario.id === 'typography' ? <TypographyScenario /> : null}
      </section>

      <dl className="runtime-evidence" aria-label="参考运行时证据">
        <div>
          <dt>commit</dt>
          <dd>{REFERENCE_BASELINE.commit}</dd>
        </div>
        <div>
          <dt>source</dt>
          <dd data-testid="reference-source">{scenario.referenceSource ?? 'shared harness'}</dd>
        </div>
      </dl>
    </main>
  );
}
